# Generated by Django 2.0.4 on 2018-04-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='about_us',
            new_name='page_content',
        ),
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
