# Generated by Django 2.0.4 on 2018-04-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180419_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
